POST http://localhost:3001/api/notes 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vYnVuYWdhIiwiaWQiOiI2MzAzMjg1YzBlMjFiZjc3MDc3MWY3NTkiLCJpYXQiOjE2NjI1MzExMTN9.41yPLstO3wgBsn6yCK22nLC80MXLXj11sIKaH2jSVy4

{
    "content": "Single Page Apps use token authentication",
    "important": true
}